### ISSUE TITLE
Gitpod fails to build/compile

### ISSUE THREAD

**Issue by seanpmyers** [sycamore-rs/sycamore-rocket-template#2]
Hey, I was trying to use Gitpod to open this project but it failed to compile with the following error:
```
error: there is no argument named `tag`
   --> /workspace/.cargo/registry/src/github.com-1ecc6299db9ec823/sycamore-macro-0.8.0-beta.2/src/view/parse.rs:117:18
    |
117 |                 "{tag}-{extended}",
    |                  ^^^^^

error: could not compile `sycamore-macro` due to previous error
```

**Comment by lukechu10** [comment]
Unfortunately that's because gitpod doesn't have the latest Rust toolchain in their base image. We'll have to wait for them to update Rust to at least 1.58 for this to be fixed. In the meantime, you can manually run `rustup override set stable && rustup target add wasm32-unknown-unknown` to update to the latest stable toolchain

**Comment by seanpmyers** [comment]
I see that makes sense.
Thanks Luke!
